### PR TITLE
#13 Admin should be able to disable an account for various reasons

### PR DESCRIPTION
**Pull request by sostene12**
#### What does this PR do?
- Admin should be able to disable an account for various reasons
#### Description of Task to be completed
- implement report illegal activity
- implement disable account done by only admin
- implement disable account depending on illegal activity reported
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ft-disableAccount
- create a .env file and put the required environment variables from .env.example file
- run migrations,and seeds 
- run the endpoint `http:localhost/api/report/create`
- run disable endpoint `http:localhost/api/vendor/disable/<vendorId>`
#### What are the relevant pivotal tracker stories?
-  [Admin should be able to disable an account for various reasons](https://trello.com/c/5ZW99vNu)

### CODE REVIEW

**Comment by sostene12** [comment]
[Admin should be able to disable an account for various reasons](https://trello.com/c/5ZW99vNu/13-admin-should-be-able-to-disable-an-account-for-various-reasons)

**Review by patsicko — CHANGES_REQUESTED** [review]
Great work!  Recheck why the two tests are failing!

**Comment by sostene12** [comment]
> Great work! Recheck why the two tests are failing!

i made changes, now they are passing

**Review by wakaflorien — APPROVED** [review]

**Review by wakaflorien — APPROVED** [review]

**Review by Luciefifi — APPROVED** [review]
Good work

**Review by wakaflorien — APPROVED** [review]

**Comment by sostene12** [comment]
> Great work! Recheck why the two tests are failing!

the tests are passing now

**Review by patsicko — APPROVED** [review]

**Pull request merged**
