### PR TITLE
ch: appsetup

### PR DESCRIPTION
**Pull request by sostene12**
#### What does this PR do?
-implement project setup
#### Description of Task to be completed
-implement project structure(folder structure)
-implement welcome endpoint
-implement API documentation with swagger
#### How should this be manually tested?
-clone the repo using git clone repo's URL
-change branch git checkout ch-appsetup
-create a .env file and put the required environment variables from .env.example file
-make a GET request in the browser and go to /docs on the documentation
#### What are the relevant pivotal tracker stories?
-Set up Node.js REST API empty project.

### CODE REVIEW

**Review by mukunzidd — CHANGES_REQUESTED** [review]
- Create a lint script to automatically lint the files
- You need to format or auto-format all the js files with the eslint-prettier setup that you have
- Please return json instead of your H2 on the test endpoint.

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- Change the port to a number that is not reserved for an HTTP code.

**Review by wakaflorien — APPROVED** [review]

**Review by patsicko — CHANGES_REQUESTED** [review]
I may suggest that you fix or remove the script "lint:fix":"eslint --fix" since it seems that it is not working.

**Review by patsicko — APPROVED** [review]
I may suggest that you fix or remove the script "lint:fix":"eslint --fix" since it seems that it is not working.

**Review by wakaflorien — APPROVED** [review]

**Review by patsicko — APPROVED** [review]

**Review by patsicko — APPROVED** [review]

**Comment by wakaflorien** [comment]
> * Create a lint script to automatically lint the files
> * You need to format or auto-format all the js files with the eslint-prettier setup that you have
> * Please return json instead of your H2 on the test endpoint.

@mukunzidd These reviews were addressed on **fixing Eslint**

**Review by mukunzidd — COMMENTED** [review]
Looks good.

**Pull request merged**
