### PR TITLE
ft(search):product search

### PR DESCRIPTION
**Pull request by sostene12**
#### What does this PR do?
- search product
#### Description of Task to be completed
- implement searching product by name, description,owner,...
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ch-ft-productSearch 
- create a .env file and put the required environment variables from .env.example file
- run migrations,and seeds 
- run the endpoint `http:localhost/api/product/search?searchParam=<something>`
#### What are the relevant pivotal tracker stories?
-  [A user should be able to search a product](https://trello.com/c/bVPkI0B2)

### CODE REVIEW

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Comment by sostene12** [comment]
[A user should be able to search a product](https://trello.com/c/bVPkI0B2/22-a-user-should-be-able-to-search-a-product)

**Review by chrill-christella — APPROVED** [review]

**Review by patsicko — APPROVED** [review]

**Review by oliviertech212 — COMMENTED** [review]
great job

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- Correct and improve failed tests.
- Write more testcases for product search.
- PR description says **/api/products/** while the code says **/api/product/**.
- PR description says **/api/products/search** while the code says **/searcch**.

**Review by wakaflorien — APPROVED** [review]

**Pull request merged**
