### PR TITLE
Ft reset password

### PR DESCRIPTION
**Pull request by Luciefifi**
# What does this PR do 
implements the functionality for resetting password

# description of the task to be completed
. Create a reset password route and controller function that generates a unique token and sends a password reset email to the user's registered email address.
. Create a route and controller function for resetting the password using the token sent to the user's email address.
.Add necessary validation checks to ensure the token is valid and not expired before allowing the password reset.
.Update the user's password in the database and log them in automatically after the password reset is successful.

# How should this be manually tested
. clone this repository
. cd into it
.run `npm install`
. add .env file
.run `npm run migrate:up` to add all migrations
.run `npm run db:seed`
.start the server by `npm run dev`
.in post man send post request `localhost://{PORT}/api/user/requestReset` to request reset token
.make a post request also `localhost://{PORT}/api/user/resetpassword/{token}` to reset your password

# relevant pivotal trscker user story
#7

### CODE REVIEW

**Review by oliviertech212 — COMMENTED** [review]
try to work on your test

**Review by Shumba250 — APPROVED** [review]
work on the tests

**Review by chrill-christella — APPROVED** [review]

**Review by oliviertech212 — COMMENTED** [review]
solve conflicts

**Comment by Luciefifi** [comment]
> solve conflicts

**Review by patsicko — APPROVED** [review]

**Review by oliviertech212 — APPROVED** [review]

**Pull request merged**
